"""empty message

Revision ID: 329e7cf495a7
Revises: f22990790f98
Create Date: 2025-05-03 17:36:18.938369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329e7cf495a7'
down_revision = 'f22990790f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
